export const CURRENCIES = [
  {
    value: "ada",
    label: "ADA",
    name: "Cardano",
    type: "crypto",
  },
  {
    value: "algo",
    label: "ALGO",
    name: "Algorand",
    type: "crypto",
  },
  {
    value: "ars",
    label: "ARS",
    name: "Argentine Peso",
    type: "fiat",
  },
  {
    value: "avax",
    label: "AVAX",
    name: "Avalanche",
    type: "crypto",
  },
  {
    value: "bnb",
    label: "BNB",
    name: "Binance Coin",
    type: "crypto",
  },
  {
    value: "bob",
    label: "BOB",
    name: "Bolivian Bolíviano",
    type: "fiat",
  },
  {
    value: "brl",
    label: "BRL",
    name: "Brazilian Real",
    type: "fiat",
  },
  {
    value: "btc",
    label: "BTC",
    name: "Bitcoin",
    type: "crypto",
  },
  {
    value: "busd",
    label: "BUSD",
    name: "Binance USD",
    type: "crypto",
  },
  {
    value: "cad",
    label: "CAD",
    name: "Canadian Dollar",
    type: "fiat",
  },
  {
    value: "clp",
    label: "CLP",
    name: "Chilean Peso",
    type: "fiat",
  },
  {
    value: "cop",
    label: "COP",
    name: "Colombian Peso",
    type: "fiat",
  },
  {
    value: "dai",
    label: "DAI",
    name: "DAI",
    type: "crypto",
  },
  {
    value: "dot",
    label: "DOT",
    name: "Polkadot",
    type: "crypto",
  },
  {
    value: "eth",
    label: "ETH",
    name: "Ethereum",
    type: "crypto",
  },
  {
    value: "eur",
    label: "EUR",
    name: "Euro",
    type: "fiat",
  },
  {
    value: "gbp",
    label: "GBP",
    name: "British Pound",
    type: "fiat",
  },
  {
    value: "ltc",
    label: "LTC",
    name: "Litecoin",
    type: "crypto",
  },
  {
    value: "matic",
    label: "MATIC",
    name: "Polygon",
    type: "crypto",
  },
  {
    value: "mxn",
    label: "MXN",
    name: "Mexican Peso",
    type: "fiat",
  },
  {
    value: "nexo",
    label: "NEXO",
    name: "NEXO",
    type: "crypto",
  },
  {
    value: "paxg",
    label: "PAXG",
    name: "PAX Gold",
    type: "crypto",
  },
  {
    value: "pen",
    label: "PEN",
    name: "Peruvian Sol",
    type: "fiat",
  },
  {
    value: "pyg",
    label: "PYG",
    name: "Paraguayan Guaraní",
    type: "fiat",
  },
  {
    value: "sol",
    label: "SOL",
    name: "Solana",
    type: "crypto",
  },
  {
    value: "usd",
    label: "USD",
    name: "US Dollar",
    type: "fiat",
  },
  {
    value: "usdc",
    label: "USDC",
    name: "USD Coin",
    type: "crypto",
  },
  {
    value: "usdt",
    label: "USDT",
    name: "Tether",
    type: "crypto",
  },
  {
    value: "uyu",
    label: "UYU",
    name: "Uruguayan Peso",
    type: "fiat",
  },
  {
    value: "xaut",
    label: "XAUT",
    name: "Tether Gold",
    type: "crypto",
  },
];
