export const PROVIDERS = [
  {
    value: "mercado-pago",
    label: "Mercado Pago",
    color: "#2abcff",
    type: "transactional",
  },
  {
    value: "provincia",
    label: "Provincia",
    color: "#279e38",
    type: "transactional",
  },
  {
    value: "cuenta-dni",
    label: "Cuenta DNI",
    color: "#279e38",
    type: "transactional",
  },
  {
    value: "nacion",
    label: "Nacion",
    color: "#005f86",
    type: "transactional",
  },
  {
    value: "santander",
    label: "Santander",
    color: "#ea1d25",
    type: "transactional",
  },
  {
    value: "galicia",
    label: "Galicia",
    color: "#e86e2c",
    type: "transactional",
  },
  {
    value: "bbva",
    label: "BBVA Frances",
    color: "#0e2043",
    type: "transactional",
  },
  {
    value: "hipotecario",
    label: "Hipotecario",
    color: "#f47321",
    type: "transactional",
  },
  {
    value: "brubank",
    label: "Brubank",
    color: "#614ad9",
    type: "transactional",
  },
  {
    value: "binance",
    label: "Binance",
    color: "#f3ba2f",
    type: "investment",
  },
  {
    value: "macro",
    label: "Macro",
    color: "#232b54",
    type: "transactional",
  },
  {
    value: "ciudad",
    label: "Ciudad",
    color: "#2350a9",
    type: "transactional",
  },
  {
    value: "supervielle",
    label: "Superville",
    color: "#840041",
    type: "transactional",
  },
  {
    value: "belo",
    label: "Belo",
    color: "#590de5",
    type: "investment",
  },
  // {
  //   value: "iol",
  //   label: "Invertir Online",
  //   type: "investment",
  // },
  {
    value: "nexo",
    label: "Nexo",
    color: "#0a0d11",
    type: "investment",
  },
  {
    value: "paypal",
    label: "Paypal",
    color: "#002991",
    type: "transactional",
  },
  {
    value: "trust",
    label: "Trust Wallet",
    color: "#0500ff",
    type: "investment",
  },
  {
    value: "cash",
    label: "Efectivo",
    color: "#66bb6a",
    type: "transactional",
  },
  {
    value: "generic",
    label: "Genérico",
    color: "#999999",
    type: "transactional",
  },
  {
    value: "credicoop",
    label: "Credicoop",
    color: "#615c50",
    type: "transactional",
  },
  {
    value: "hsbc",
    label: "HSBC",
    color: "#db0011",
    type: "transactional",
  },
  {
    value: "icbc",
    label: "ICBC",
    color: "#b81e2d",
    type: "transactional",
  },
  {
    value: "itau",
    label: "Itaú",
    color: "#ff6200",
    type: "transactional",
  },
  {
    value: "balanz",
    label: "Balanz",
    color: "#0d2055",
    type: "investment",
  },
  {
    value: "modo",
    label: "MODO",
    color: "#008859",
    type: "transactional",
  },
  {
    value: "prex",
    label: "Prex",
    color: "#5a50f9",
    type: "transactional",
  },
  {
    value: "naranja-x",
    label: "Naranja X",
    color: "#fe5000",
    type: "transactional",
  },
  {
    value: "uala",
    label: "Ualá",
    color: "#ff5874",
    type: "transactional",
  },
  {
    value: "dolar-app",
    label: "Dolar App",
    color: "#22d081",
    type: "investment",
  },
  {
    value: "cocos-investment",
    label: "Cocos investment",
    color: "#8e4ec6",
    type: "investment",
  },
  {
    value: "lemon",
    label: "Lemon",
    color: "#00f068",
    type: "investment",
  },
  {
    value: "ripio",
    label: "Ripio",
    color: "#7908ff",
    type: "investment",
  },
  {
    value: "satoshi-tango",
    label: "Satoshi Tango",
    color: "#51ebc0",
    type: "investment",
  },
  {
    value: "takenos",
    label: "Takenos",
    color: "#6d37d5",
    type: "investment",
  },
  {
    value: "buenbit",
    label: "Buenbit",
    color: "#ffabea",
    type: "investment",
  },
];
